use_syn: False
resolution: 512
masked_training: True
uniform_yaw: False
pretrain_just_disabled: True
autobackup_hour: 4
write_preview_history: True
target_iter: 14
random_flip: True
face_type: wf
models_opt_on_gpu: True
archi: liae-ud
ae_dims: 256
e_dims: 128
d_dims: 128
d_mask_dims: 32
eyes_prio: False
lr_dropout: False
random_warp: False
gan_power: 0.0
true_face_power: 0.0
face_style_power: 0.0
bg_style_power: 0.0
ct_mode: none
clipgrad: True
pretrain: False
